source(file.path("..", "..", "config", "simulation.R"))
source(file.path("..", "..", "R", "build_model.R"))
source(file.path("..", "..", "R", "extract_outcomes.R"))
source(file.path("..", "..", "R", "simulate.R"))
source(file.path("..", "..", "R", "calibrate.R"))
source(file.path("..", "..", "R", "masking.R"))
source(file.path("..", "..", "config", "multiscale.R"))
source(file.path("..", "..", "R", "within_host.R"))
source(file.path("..", "..", "R", "omics.R"))
source(file.path("..", "..", "R", "reproduction.R"))
source(file.path("..", "..", "R", "multiscale.R"))
source(file.path("..", "..", "R", "multiscale_abm.R"))
if (requireNamespace("torch", quietly = TRUE)) {
  source(file.path("..", "..", "R", "torch_model.R"))
  source(file.path("..", "..", "R", "fit_models.R"))
  source(file.path("..", "..", "R", "export_web_model.R"))
  predict_path <- file.path("..", "..", "R", "predict.R")
  if (file.exists(predict_path)) source(predict_path)
  source(file.path("..", "..", "R", "multimodal_emulator.R"))
}
